server:
  port: 8080

person:
  name: gujiangbo
  age: 28
  birth: 1989/11/12
  lists:
    - lisi
    - wangwu
  dog:
    name: xiaoli
    age: 2

spring:
  datasource:
    username: gujiangbo
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://172.16.121.130:3306/webapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

mybatis:
  mapper-locations: classpath:sql/*_map.xml
  type-aliases-package: com.gujiangbo.application.info

