server:
  port: 8099

person:
  name: gujiangbo
  age: 28
  birth: 1989/11/12
  lists:
    - lisi
    - wangwu
  dog:
    name: xiaoli
    age: 2

spring:
  datasource:
    username: gujiangbo
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
#  rabbitmq:
#    host: 172.16.121.130
#    port: 5672
#    username: gujiangbo
#    password: 56rt%^RT
#    virtual-host: vhost

mybatis:
  mapper-locations: classpath:sql/*_map.xml
  type-aliases-package: com.gujiangbo.application.info

